// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7AXhkTJTg5j5xWgBJjS8dRV8oZXfTEMQ',
    appId: '1:407855852221:android:9930db9b3571bad8f9e5d4',
    messagingSenderId: '407855852221',
    projectId: 'totel-d7322',
    storageBucket: 'totel-d7322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6H7yc46mrseC3ABYOjz9jvG3tdWeHniA',
    appId: '1:407855852221:ios:b2263fa603dade42f9e5d4',
    messagingSenderId: '407855852221',
    projectId: 'totel-d7322',
    storageBucket: 'totel-d7322.appspot.com',
    androidClientId: '407855852221-3cfgj728ubsn4e3q7edhem2kaep0edej.apps.googleusercontent.com',
    iosClientId: '407855852221-dekodiuo3tdg6lnsmc2jscrdk40o2a5i.apps.googleusercontent.com',
    iosBundleId: 'com.oluhagroup.totelpartner',
  );
}
