// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Stb-uqUctfhQFevoJMT6b-AxQQGEKyI',
    appId: '1:744932631176:web:1ff829f383c6fd354cf53d',
    messagingSenderId: '744932631176',
    projectId: 'totel-debug',
    authDomain: 'totel-debug.firebaseapp.com',
    storageBucket: 'totel-debug.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBnlv5sCeEw4WXS8qmKyLocpMGDLRWVM',
    appId: '1:744932631176:android:2ee73ef2b764d7534cf53d',
    messagingSenderId: '744932631176',
    projectId: 'totel-debug',
    storageBucket: 'totel-debug.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcZSlA26qG37SC1YLSlk6hrB27h7IkBvA',
    appId: '1:744932631176:ios:fae30ec9224bc06d4cf53d',
    messagingSenderId: '744932631176',
    projectId: 'totel-debug',
    storageBucket: 'totel-debug.appspot.com',
    iosClientId:
        '744932631176-eschpe33qtal48bb8gruvhb7c9b9nloc.apps.googleusercontent.com',
    iosBundleId: 'com.example.totel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcZSlA26qG37SC1YLSlk6hrB27h7IkBvA',
    appId: '1:744932631176:ios:fae30ec9224bc06d4cf53d',
    messagingSenderId: '744932631176',
    projectId: 'totel-debug',
    storageBucket: 'totel-debug.appspot.com',
    iosClientId:
        '744932631176-eschpe33qtal48bb8gruvhb7c9b9nloc.apps.googleusercontent.com',
    iosBundleId: 'com.example.totel',
  );
}
